accounts/urls.py
from django.urls import path
from django.contrib.auth import views as authviews
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', authviews.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', authviews.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('profile/', views.Profile.as_view(), name='profile')
]

holiday_planner/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexPage.as_view(), name='index'),
    path('accounts/', include('accounts.urls'), name='accounts'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('placesofinterest/', include('locations.urls'), name='locations')
]

locations/urls.py
from django.urls import path
from . import views

app_name = 'locations'

urlpatterns = [
    path('restaurants/', views.RestaurantList.as_view(), name='restaurants'),
    path('hotels/', views.HotelList.as_view(), name='hotels'),
    path('lodges/', views.LodgeList.as_view(), name='lodges'),
    path('resorts/', views.ResortList.as_view(), name='resorts')
]

locations/models.py
from django.db import models

# Create your models here.
class Accommodations(models.Model):
    ACCOMMODATION_TYPES = [
        ('hotel', 'Hotel'),
        ('resort', 'Resort'),
        ('restaurant', 'Restaurant'),
        ('lodge', 'Lodge'),
    ]

    name = models.CharField(max_length=100, primary_key=True)
    province = models.CharField(max_length=50)
    town = models.CharField(max_length=100)
    type = models.CharField(
        max_length=20,
        choices=ACCOMMODATION_TYPES,
        default='hotel'
    )
    
    img_url = models.ImageField(upload_to='locations/static/images/', blank=True, null=True)

    
    def __str__(self):
        return self.name
    

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

class UserCreateForm(UserCreationForm):

    class Meta():
        fields = ('username', 'email', 'password1', 'password2')
        model = get_user_model()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Display Name'
        self.fields['email'].label = "Email Address"

accounts/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from . import forms
from django.views.generic import CreateView, TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
# Create your views here.

class SignUp(CreateView):
    form_class = forms.UserCreateForm
    success_url = reverse_lazy('login')

    template_name = 'accounts/signup.html'

class Profile(LoginRequiredMixin, TemplateView):

    template_name = 'accounts/profile.html'

holiday_planner/views.py
from django.views.generic import TemplateView

class IndexPage(TemplateView):
    template_name = 'index.html'

locations/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Accommodations
import os

# Create your views here.
class RestaurantList(ListView):
    model = Accommodations
    template_name = 'locations/restaurant_list.html'
    context_object_name = 'restaurants'

    def get_queryset(self):
        return super().get_queryset().filter(type='restaurant')
    
class HotelList(ListView):
    model = Accommodations
    template_name = 'locations/hotel_list.html'
    context_object_name = 'hotels'

    def get_queryset(self):
        return super().get_queryset().filter(type='hotel')
    
class ResortList(ListView):
    model = Accommodations
    template_name = 'locations/resort_list.html'
    context_object_name = 'resorts'

    def get_queryset(self):
        return super().get_queryset().filter(type='resort')
    
class LodgeList(ListView):
    model = Accommodations
    template_name = 'locations/lodge_list.html'
    context_object_name = 'lodges'

    def get_queryset(self):
        return super().get_queryset().filter(type='lodge')
    

accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
    <div class='container'>
        <h1>Login</h1>
        <form method="POST">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class='btn btn-default' value='login'>
        </form>
    </div>
{% endblock  %}

accounts/templates/accounts/profile.html
{% extends "base.html" %}
{% block content %}
    <div>
        <p>{{user.email}}</p>
    </div>
{% endblock  %}

accounts/templates/accounts/signup.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
    <div class='container'>
        <h1>Signup</h1>
        <form method="POST">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class='btn btn-default' value='signup'>
        </form>
    </div>
{% endblock  %}

locations/templates/locations/hotel_list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    {% for places in hotels %}
        <p>{{places.name}}</p>
        <img src="{% static places.img_url.url|slice:'17:' %}" alt="">
    {% endfor %}
{% endblock  %}

locations/templates/locations/lodge_list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    {% for places in lodges %}
        <p>{{places.name}}</p>
        <img src="{% static places.img_url.url|slice:'17:' %}" alt="">
    {% endfor %}
{% endblock  %}

locations/templates/locations/resort_list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    {% for places in resorts %}
        <p>{{places.name}}</p>
        <img src="{% static places.img_url.url|slice:'17:' %}" alt="">
    {% endfor %}
{% endblock  %}

locations/templates/locations/restaurant_list.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    {% for places in restaurants %}
        <p>{{places.name}}</p>
        <img src="{% static places.img_url.url|slice:'17:' %}" alt="">
    {% endfor %}
{% endblock  %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css"/>
    <link rel="stylesheet" href="{% static "css/master.css" %}">
    <title>Document</title>
</head>
<body>
    <div class='sticky-top'>
        <nav class="navbar navbar-expand-lg bg-body-tertiary sticky-top navbar-custom">
            <div class="container-fluid">
                <a class="navbar-brand nav-element-custom nav-brand-custom me-4" href="/">Holiday SA</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>
                    <form class="d-flex me-4 nav-search-custom" role="search">
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search"/>
                    <button class="btn btn-outline-success" type="submit">Search</button>
                    </form>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link nav-element-custom" href="#">Discover</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link nav-element-custom" href="#">News Letter</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link nav-element-custom" href="#">Donate</a>
                    </li>
                </ul>
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">

                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a href="{% url "accounts:profile" %}" class="nav-link nav-element-custom">
                                <i class="bi bi-person-circle"></i>
                            </a>
                        </li>
                        <li class="nav-item">
                            <form action="{% url 'accounts:logout' %}" method="post" style="display:inline;">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-link nav-link nav-element-custom" style="display:inline; border:none; background:none;">
                                    Logout
                                </button>
                            </form>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link nav-element-custom" href="{% url "accounts:login" %}">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link nav-element-custom" href="{% url "accounts:signup" %}">Signup</a>
                        </li>
                    {% endif %}
                </ul>
                </div>
            </div>
        </nav>

        <nav class="navbar navbar-expand-lg bg-body-tertiary navbar-custom-bottom">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item nav-first-element-custom me-3">
                    <a class="nav-link " href="{% url "locations:hotels" %}">Hotels</a>
                    </li>
                    <li class="nav-item me-3">
                    <a class="nav-link" href="{% url "locations:restaurants" %}">Restaurants</a>
                    </li>
                    <li class="nav-item me-3">
                    <a class="nav-link" href="#">Activities</a>
                    </li>
                    <li class="nav-item me-3">
                    <a class="nav-link" href="{% url "locations:resorts" %}">Resorts</a>
                    </li>
                    <li class="nav-item me-3">
                    <a class="nav-link" href="{% url "locations:lodges" %}">Lodges</a>
                    </li>
                    <li class="nav-item me-3">
                    <a class="nav-link" href="#">Flights</a>
                    </li>
                    <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Provinces
                    </a>
                    <ul class="dropdown-menu">
                        <li class="nav-item dropdown">
                        <li><a class="dropdown-item" href="#">Gauteng</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="#">KwaZulu-Natal</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="#">Eastern Cape</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="#">Western Cape</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="#">Northern Cape</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="#">Limpopo Cape</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="#">Free State</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="#">North-West</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="#">Mpumalanga</a></li>
                    </ul>
                    </li>
                    <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Fauna and Flora
                    </a>
                    <ul class="dropdown-menu">
                        <li class="nav-item dropdown">
                        <li><a class="dropdown-item" href="#">Mammals</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="#">Birds</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="#">Insects</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="#">Marine Life</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="#">Plants</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="#">Trees</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><a class="dropdown-item" href="#">Fungi</a></li>
                        <li><hr class="dropdown-divider"></li>
                    </ul>
                    </li>
                </ul>
                 
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    <li class="nav-item me-3">
                    <a class="nav-link" href="#">About</a>
                    </li>   
                    <li class="nav-item me-3">
                    <a class="nav-link" href="#">Contact</a>
                    </li> 
                </ul>
                </div>
            </div>
        </nav>
    </div>
    {% block content %}
    {% endblock  %}
</body>
<script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
<script src="{% static "js/master.js"%}" type="text/javascript" ></script>
</html>

templates/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <div "col-md-12 container">
        <div class="col-md-2"></div>
        <div id="carouselExampleAutoplaying" class="col-md-8 offset-md-2 carousel slide carousel-custom" data-bs-ride="carousel">
            <div class="carousel-inner">
                <div class="carousel-item active">
                <img src="{% static "images/slide_1.jpg" %}" class="d-block w-100" alt="...">
                </div>
                <div class="carousel-item">
                <img src="{% static "images/slide_2.jpg" %}" class="d-block w-100" alt="...">
                </div>
                <div class="carousel-item">
                <img src="{% static "images/slide_3.jpg" %}" class="d-block w-100" alt="...">
                </div>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleAutoplaying" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
            </button>
        </div>
        <div class="col-md-2 offset-md-10"></div>
        <div class='container col-md-12'>
            <h1>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Iste beatae neque earum placeat minus cum maxime animi obcaecati doloremque facere aspernatur, reiciendis dignissimos sunt alias culpa delectus incidunt eligendi eaque.</h1>
            <h1>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Iste beatae neque earum placeat minus cum maxime animi obcaecati doloremque facere aspernatur, reiciendis dignissimos sunt alias culpa delectus incidunt eligendi eaque.</h1>
            <h1>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Iste beatae neque earum placeat minus cum maxime animi obcaecati doloremque facere aspernatur, reiciendis dignissimos sunt alias culpa delectus incidunt eligendi eaque.</h1>
            <h1>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Iste beatae neque earum placeat minus cum maxime animi obcaecati doloremque facere aspernatur, reiciendis dignissimos sunt alias culpa delectus incidunt eligendi eaque.</h1>
            <div class="bar-container">
                <div class="bar bar1"></div>
            </div>

            <div class="bar-container">
                <div class="bar bar2"></div>
            </div>

            <div class="bar-container">
                <div class="bar bar3"></div>
            </div>
        </div>
    </div>

    {% endblock  %}